name: Deploy Django to Render

on:
  push:
    branches:
      - main  # This will trigger the pipeline on push to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate  # This will run database migrations if needed.

    - name: Collect static files (optional)
      run: |
        python manage.py collectstatic --noinput  # This collects static files for production.

    - name: Run tests (optional)
      run: |
        python manage.py test  # Run tests to make sure everything is working.

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Set your Render API key in GitHub secrets
      run: |
        curl -X POST https://api.render.com/v1/services/YOUR_RENDER_SERVICE_ID/deploy \
          -H "Authorization: Bearer $RENDER_API_KEY"
